# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys,configparser,os
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal
from PyQt5.QtWidgets import QApplication, QMainWindow
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.Name = pyqtSignal(str)
        MainWindow.Id = pyqtSignal(str)
        MainWindow.Lang = pyqtSignal(str)
        MainWindow.About = pyqtSignal(str)
        MainWindow.Write = pyqtSignal
        MainWindow.AutoFile = pyqtSignal
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(640, 360)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 641, 281))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 20, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei Light")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei Light")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(560, 230, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(480, 230, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(50, 220, 151, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 220, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei Light")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(50, 40, 151, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 20, 151, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei Light")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setGeometry(QtCore.QRect(50, 60, 151, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_3.setGeometry(QtCore.QRect(560, 280, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 640, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu1 = QtWidgets.QMenu(self.menuBar)
        self.menu1.setObjectName("menu1")
        self.menu2 = QtWidgets.QMenu(self.menuBar)
        self.menu2.setObjectName("menu2")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menu1.menuAction())
        self.menuBar.addAction(self.menu2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        #用了个最简单的办法直接把MainWindow改成self，但应该有办法把代码和窗体分开
        self.pushButton_2.clicked.connect(self.Write)
        self.pushButton.clicked.connect(self.lineEdit.clear)
        self.pushButton.clicked.connect(self.lineEdit_2.clear)
        self.lineEdit.textChanged['QString'].connect(self.Id)
        self.comboBox.activated['QString'].connect(self.Lang)
        self.lineEdit_2.textChanged['QString'].connect(self.Name)
        self.lineEdit_3.textChanged['QString'].connect(self.About)
        self.pushButton_3.clicked.connect(self.AutoFile)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        #定义变量，记得加self.xxx
        self.AA = None
        self.AB = None
        self.AC = None
        self.AD = None
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Name:"))
        self.label_2.setText(_translate("MainWindow", "ID:"))
        self.pushButton.setText(_translate("MainWindow", "Clear"))
        self.pushButton_2.setText(_translate("MainWindow", "Write"))
        self.comboBox.setItemText(1, _translate("MainWindow", "SimplifiedChinese.xml"))
        self.comboBox.setItemText(2, _translate("MainWindow", "English.xml"))
        self.label_3.setText(_translate("MainWindow", "Lang:"))
        self.label_4.setText(_translate("MainWindow", "About:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Lang"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "test"))
        self.pushButton_3.setText(_translate("MainWindow", "AutoFile"))
        self.menu1.setTitle(_translate("MainWindow", "File"))
        self.menu2.setTitle(_translate("MainWindow", "Setting"))
    def Name(self,text):
        print("Name输入内容:" + text)
        self.AA = text
    def Id(self,text):
        print("Id输入内容为" + text)
        self.AB = text
    def Lang(self,text):
        print("Lang输入内容为" + text)
        self.AC = text
    def About(self,text):
        print("About输入内容为" + text)
        self.AD = text
    def Write(self):
        print('生成完成')
        with open('./ModFile/' + self.AC, 'a', encoding='utf-8') as B:
            B.write('\n' + '<entityname.' + self.AB + '>' + self.AA + '</entityname.' + self.AB + '>')
            B.write('\n' + '<entitydescription.' + self.AB + '>' + self.AD + '</entitydescription.' + self.AB + '>')
    def AutoFile(self):
        config = configparser.ConfigParser()
        configname = './config.ini'
        for root, dirs, files in os.walk('./'):
            if 'config.ini' in files:
                print('检测到配置文件')
                config.read(configname, encoding='utf-8')
                # 读取cinfig目录下的config.ini
                file = config.get('run', 'file')
                # 判断是否需要初始化建立文件
                if file == '0':
                    os.mkdir('./ModFile')
                    list = {"filelist.xml", "SimplifiedChinese.xml", "English.xml", "Mods.xml"}
                    for make in list:
                        with open('./ModFile/' + make, 'w', encoding='utf-8') as A:
                            # 判断是否为语言文件,如果为true则增加语言文件的前缀
                            if make == "SimplifiedChinese.xml":
                                A.write(
                                    '<?xml version="1.0" encoding="utf-8"?>\n<infotexts language="Simplified Chinese" nowhitespace="true" translatedname="中文(简体)">')
                            if make == "English.xml":
                                A.write(
                                    '<?xml version="1.0" encoding="utf-8"?>\n<infotexts language="English" nowhitespace="false" translatedname="English">')
                            # TODO:if make == "filelist.xml":并写入内容
                            else:
                                A.write('<?xml version="1.0" encoding="utf-8"?>')
                    # 生成完成后修改配置文件
                    config.set('run', 'file', '1')
                    config.write(open(configname, 'w'))
                else:
                    print('非初始化,自动取消生成文件')
                break
            else:
                print("没有检测到配置文件，开始生成")
                config = configparser.ConfigParser()
                config['run'] = {
                    'initialization': '1',
                    'file': '0'
                }
                config.write(open('config.ini', 'w', encoding='utf-8'))
                break
if __name__ == '__main__':
    app = QApplication(sys.argv)
    Mainwindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(Mainwindow)
    Mainwindow.show()
    sys.exit(app.exec_())
